# Generated by Codex on 2026-05-26

from decimal import Decimal

from django.db import migrations


SERVICES = [
    {
        'name': 'Quick Exterior Wash',
        'description': 'Fast exterior rinse, foam wash, wheel rinse, and hand dry for a clean everyday shine.',
        'price': Decimal('12.00'),
        'duration_minutes': 25,
        'is_active': True,
    },
    {
        'name': 'Standard Wash',
        'description': 'Exterior wash plus interior vacuum, dashboard wipe-down, windows, and tire shine.',
        'price': Decimal('22.00'),
        'duration_minutes': 45,
        'is_active': True,
    },
    {
        'name': 'Premium Wash',
        'description': 'Full standard wash with wax protection, detailed wheel cleaning, and interior refresh.',
        'price': Decimal('35.00'),
        'duration_minutes': 70,
        'is_active': True,
    },
    {
        'name': 'Interior Deep Clean',
        'description': 'Focused cabin cleaning with deep vacuuming, seat and carpet shampoo, and odor refresh.',
        'price': Decimal('45.00'),
        'duration_minutes': 90,
        'is_active': True,
    },
    {
        'name': 'Full Detail Package',
        'description': 'Complete inside-and-out detail with exterior polish, wax, interior shampoo, and finishing touches.',
        'price': Decimal('75.00'),
        'duration_minutes': 150,
        'is_active': True,
    },
    {
        'name': 'Engine Bay Cleaning',
        'description': 'Careful engine bay degreasing and wipe-down to remove buildup and improve presentation.',
        'price': Decimal('30.00'),
        'duration_minutes': 50,
        'is_active': True,
    },
]


def seed_services(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    for service in SERVICES:
        Service.objects.update_or_create(
            name=service['name'],
            defaults=service,
        )


def remove_seeded_services(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    Service.objects.filter(name__in=[service['name'] for service in SERVICES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_services, remove_seeded_services),
    ]
