# Generated by Codex on 2026-05-26

from django.db import migrations


SERVICE_TRANSLATIONS = [
    (
        'Quick Exterior Wash',
        'Lavage extérieur rapide',
        'Rinçage extérieur, mousse, nettoyage des jantes et séchage à la main pour une brillance rapide au quotidien.',
    ),
    (
        'Standard Wash',
        'Lavage standard',
        'Lavage extérieur avec aspiration intérieure, nettoyage du tableau de bord, vitres et brillance des pneus.',
    ),
    (
        'Premium Wash',
        'Lavage premium',
        'Lavage standard complet avec protection à la cire, nettoyage détaillé des jantes et rafraîchissement intérieur.',
    ),
    (
        'Interior Deep Clean',
        'Nettoyage intérieur profond',
        'Nettoyage ciblé de l’habitacle avec aspiration approfondie, shampoing des sièges et tapis, et traitement des odeurs.',
    ),
    (
        'Full Detail Package',
        'Detailing complet',
        'Detailing intérieur et extérieur avec polissage, cire, shampoing intérieur et finitions soignées.',
    ),
    (
        'Engine Bay Cleaning',
        'Nettoyage moteur',
        'Dégraissage et essuyage soigneux du compartiment moteur pour enlever les dépôts et améliorer la présentation.',
    ),
]

REVERSE_TRANSLATIONS = [
    (
        'Lavage extérieur rapide',
        'Quick Exterior Wash',
        'Fast exterior rinse, foam wash, wheel rinse, and hand dry for a clean everyday shine.',
    ),
    (
        'Lavage standard',
        'Standard Wash',
        'Exterior wash plus interior vacuum, dashboard wipe-down, windows, and tire shine.',
    ),
    (
        'Lavage premium',
        'Premium Wash',
        'Full standard wash with wax protection, detailed wheel cleaning, and interior refresh.',
    ),
    (
        'Nettoyage intérieur profond',
        'Interior Deep Clean',
        'Focused cabin cleaning with deep vacuuming, seat and carpet shampoo, and odor refresh.',
    ),
    (
        'Detailing complet',
        'Full Detail Package',
        'Complete inside-and-out detail with exterior polish, wax, interior shampoo, and finishing touches.',
    ),
    (
        'Nettoyage moteur',
        'Engine Bay Cleaning',
        'Careful engine bay degreasing and wipe-down to remove buildup and improve presentation.',
    ),
]


def translate_services(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    for old_name, new_name, new_description in SERVICE_TRANSLATIONS:
        Service.objects.filter(name=old_name).update(name=new_name, description=new_description)


def reverse_translate_services(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    for old_name, new_name, new_description in REVERSE_TRANSLATIONS:
        Service.objects.filter(name=old_name).update(name=new_name, description=new_description)


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_seed_initial_services'),
    ]

    operations = [
        migrations.RunPython(translate_services, reverse_translate_services),
    ]
