# Generated by Codex on 2026-05-26

from django.db import migrations, models


def map_old_car_types(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    Booking.objects.filter(car_type__in=['suv', 'truck', 'van']).update(car_type='four_by_four')
    Booking.objects.filter(car_type__in=['sedan', 'coupe', 'hatchback', 'other']).update(car_type='small_car')


def reverse_car_type_mapping(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    Booking.objects.filter(car_type='four_by_four').update(car_type='suv')
    Booking.objects.filter(car_type='small_car').update(car_type='sedan')


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_public_customer_details'),
    ]

    operations = [
        migrations.RunPython(map_old_car_types, reverse_car_type_mapping),
        migrations.AlterField(
            model_name='booking',
            name='car_type',
            field=models.CharField(
                choices=[
                    ('small_car', 'Small Car'),
                    ('four_by_four', '4x4'),
                    ('motorcycle', 'Motorcycle'),
                ],
                max_length=20,
            ),
        ),
    ]
