# Generated by Django 4.2.30 on 2026-05-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_update_car_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='car_type',
            field=models.CharField(choices=[('small_car', 'Petite voiture'), ('four_by_four', '4x4'), ('motorcycle', 'Moto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('done', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
    ]
