# Generated by Django 6.0.2 on 2026-05-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_car_type_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer_email',
        ),
    ]
