# Generated by Django 6.0.2 on 2026-05-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_booking_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='car_brand',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='car_color',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='car_plate',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='car_type',
        ),
    ]
