# Generated by Django 6.0.2 on 2026-05-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_booking_car_brand_remove_booking_car_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
